config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  get "search", to: "dreams#search"
  resources :dreams do
    resources :locations, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :meetings, only: [:new, :create]
  end
  resources :meetings, only: [:show, :index, :destroy]
  resources :chatrooms, only: [:show, :index, :new, :create] do
    resources :messages, only: [:create]
  end

  
end

app/models/dream.rb
class Dream < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :locations, dependent: :destroy

  after_validation :geocode, if: :will_save_change_to_name_street?

  geocoded_by :address

  validates :name, :description, :regions, presence: :true
  validates :description, length: { in: 10..500}

  def address
    "#{number_street} #{name_street} #{post_code} #{city}"
  end


end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
  # skip_before_action :authenticate_user!, only: %i[index show]
  # before_action :set_dream, only: %i[show edit update destroy]

  def index
    @dreams = FilterDreamsService.new(params[:regions]).call

    #ici je filtre les dreams
    if params[:query].present?
      @dreams = @dreams.where("name ILIKE ?", "%#{params[:query]}%")
    end

    @markers = @dreams.geocoded.map do |dream|
      {
        lat: dream.latitude,
        lng: dream.longitude,
        id: dream.id,
        # info_window: { render_to_string partial: "info_window", locals: { dreams: @dreams}, formats: [:html] },
        info_window: render_to_string(partial: "info_window", locals: { dream: dream }, formats: [:html]),
      }
    end

    respond_to do |format|
      format.html
      format.text { render partial: "dreams_list", locals: { dreams: @dreams }, formats: [:html] }
    end

  end

  def show
    @dream = Dream.find(params[:id])
    @meeting = Meeting.new
  end

  def new
    @dream = Dream.new
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user = current_user
    if @dream.save
      redirect_to dreams_path(@dream)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @dream = Dream.find(params[:id])
    if @dream.update(dream_params)
      redirect_to dreams_path(@dream), notice: "dream was successfully updated."
    else
      render :edit, notice: "dreams was not updated."
    end
  end

  def destroy
    @dream = Dream.find(params[:id])
    @dream.destroy
    redirect_to dreams_path, notice: "dreams was successfully destroyed."
  end

  private

  def dream_params
    params.require(:dream).permit(:name, :description, :address, :activity, :region, :img_url_one, :img_url_two)
  end

  def set_dream
    @dream = Dream.find(params[:id])
  end

end

app/views/dreams/_dreams_list.html.erb
<div class="b-box" data-controller="dreams">
  <div class="card-for-img-and-mapbox">
    <% @dreams.each do |dream| %>
  <div class="div-card" data-action="mouseenter->dreams#onCard" data-id="<%= dream.id %>">
<div class="image-container">
  <%= link_to(image_tag(dream.img_url_one, class: 'image'), dream_path(dream)) %>
  <div class="spot-heart">
    <% if user_signed_in? %>
      <% if current_user.likes.exists?(dream: dream) %>
        <%= button_to dream_like_path(dream, current_user.likes.find_by(dream: dream)), method: :delete, remote: true, class: "buttons", data: { like_id: current_user.likes.find_by(dream: dream)&.id, liked: current_user.likes.find_by(dream: dream).present? }, type: "button" do %>
          <i class="fa-solid fa-heart" data-controller="like" data-like-target="heart" data-like-action="click->like#toggle"></i>
        <% end %>
      <% else %>
        <%= button_to dream_likes_path(dream), method: :post, remote: true, class: "button-like", data: { dream_id: dream.id }, type: "button" do %>
          <i class="fa-regular fa-heart" data-controller="like" data-like-target="heart" data-like-action="click->like#toggle"></i>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>


      <h5><%= dream.name %></h5>
      <div class="dream-dreamd-actions">
        <%= link_to "Plus d'informations", dream_path(dream), class: "link_to_infos" %>
      </div>
    </div>
    <% end %>
  </div>

<% if @dreams.any? %>
  <div class="index-map">
    <div style="width: 450px; height: 100vh"
      data-controller="map"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
      data-map-markers-value="<%= @markers.to_json %>"
      data-action="point->map#popup"
      data-dreams-target="map">
    </div>
  </div>
<% end %>

app/views/dreams/_edit.html.erb
 <%= render "form", dream: @dream %>

app/views/dreams/_form.html.erb
<%= simple_form_for(dream) do |f| %>
  <%= f.input :brand %>
  <%= f.input :model %>
  <%= f.input :address %>
  <%= f.input :price_per_day %>
  <%= f.input :year_of_production %>
  <%= f.input :img_url %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/dreams/_index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our dreams</h1>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @dreams.count %> dreams out of our <%= Dream.count %> on our website.</p>
      <% else %>
        <p>All <%= Dream.count %> cars.</p>
      <% end %>
    </div>
  </div>

app/views/dreams/_info_window.html.erb
<div class="csspopup">
  <p><%= dream.name %></p>
  <%= image_tag dream.img_url_one %>
</div>

app/views/dreams/edit.html.erb
 <%= render "form", dream: @dream %>

app/views/dreams/form.html.erb
<%= simple_form_for(dream) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :regions %>
  <%= f.input :img_url_one %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/dreams/index.html.erb
<div class="title">
  <h1>Voici les rêves sur la région séléctionnée</h1>
    <div class="row">
      <div class="col">
        <% if @query %>
          <p>You searched for <strong><%= @query %></strong>. We found <%= @dreams.count %> dreams out of our <%= Dream.count %> on our website.</p>
        <% else %>
          <%# <p>Vous avez séléctionné la région <%= @dreams.first.regions.</p> %>
        <% end %>
      </div>
    </div>
</div>

<div data-controller="search">
  <%= form_with url: dreams_path, method: :get do |form| %>
    <%= image_tag("search.png", alt: "Logo", class: "form-logo") %>
    <%= form.text_field :query,
      placeholder: "Rechercher",
      autocomplete: "off",
      class: "search-form",
      data: { action: "input->search#updateDreams", search_target: "input" }
    %>
  <% end %>
  <div data-search-target="results">
    <%= render "dreams/dreams_list", locals: { dreams: @dreams } %>
  </div>
</div>

app/views/dreams/new.html.erb
<h1>Add a new dream</h1>
<%# <%= render "form", dream: @dream %>
<%= simple_form_for(@dream) do |f| %>
<%= f.input :name %>
<%= f.input :description %>

<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/dreams/show.html.erb
<div class="big-title-show">
  <h1><%= @dream.name %></h1>
</div>
<div class="text-for-show">
  <p class="car-show-address">Rappel, vous avez choisis la région: <%= @dream.regions %></p>
</div>

<div class="class-for-img" data-controller="carousel" data-target="carousel.slide">
  <img src="<%= @dream.img_url_one %>" class="show-dreams-image" data-action="click->carousel#openImage" data-carousel-target="currentImage">
  <div class="image-show-dreams" data-carousel-target="modal">
    <div class="image-modal-content">
      <span data-action="click->carousel#closeImage" class="close">&times;</span>
      <img src="" class="image" data-carousel-target="image">
    </div>
  </div>
  <div class="image-two-show-dreams" data-target="carousel.slide" data-carousel-target="slide">
    <div class="image-modal-content">
      <img src="<%= @dream.img_url_two %>" class="image-two-show-dreams" data-action="click->carousel#openImage">
      <div data-target="carousel.slide" >
        <img src="<%= @dream.img_url_three %>" class="image-two-show-dreams" data-action="click->carousel#openImage">
      </div>
    </div>
  </div>
  <div class="image-three-show-dreams" data-target="carousel.slide" data-carousel-target="slide">
    <div class="image-modal-content">
      <img src="<%= @dream.img_url_four %>" class="image-three-show-dreams" data-action="click->carousel#openImage">
        <div data-target="carousel.slide">
          <img src="<%= @dream.img_url_five %>" class="image-three-show-dreams" data-action="click->carousel#openImage">
        </div>
    </div>
  </div>
</div>


<div class="div-for-des-calandar">
  <div class="show-description">
    <h3>Details</h3>
    <%= @dream.description %>€
  </div>
  <div class="h-calendar">
    <h5> Réserve ton rêve ici !</h5>
      <div class="flatpickr-innerContainer">
        <%= simple_form_for ([@dream, @meeting]), data: { controller: 'flatpickr' } do |f| %>
          <%= f.input :start_time, as: :string, input_html: { data: {flatpickr_target: "startsAt"}}%>
          <%= f.input :end_time, as: :string, input_html: { data: {flatpickr_target: "endsAt"}, id: "end_time"}%>
          <%= f.submit 'Réserver votre rêve', class: "submit" %>
        <% end %>
      </div>
  </div>
</div>

<div class="button_class">
<%= link_to "Retourner sur la listes des rêves", dreams_path, class: "button" %>
</div>