config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  get "search", to: "dreams#search"
  resources :dreams do
    resources :locations, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :meetings, only: [:new, :create]
  end
  resources :meetings, only: [:show, :index, :destroy]
  resources :chatrooms, only: [:show, :index, :new, :create] do
    resources :messages, only: [:create]
  end

  
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :dream
  validates :start_time, :end_time, presence: true

  default_scope -> { order(:start_time) }  # Our meetings will be ordered by their start_time by default

  def time
    "#{start_time.strftime('%I:%M %p')} - #{end_time.strftime('%I:%M %p')}"
  end

  def multi_days?
    (end_time.to_date - start_time.to_date).to_i >= 1
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def index
    # Scope your query to the dates being shown:
    start_date = params.fetch(:start_date, Date.today).to_date

    # For a monthly view:
    @meetings = Meeting.where(start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)

    # Or, for a weekly view:
    @meetings = Meeting.where(start_time: start_date.beginning_of_week..start_date.end_of_week)


    @meetings = Meeting.includes(:dream).all

  end

  def show
    @meeting = Meeting.find(params[:id])
    
  end

  def new
    @meetings = Meeting.new
  end

  def create
    @dream = Dream.find(params[:dream_id])
    @meeting = Meeting.new(meeting_params)
    @meeting.dream = @dream
    @meeting.user = current_user
    if @meeting.save
      redirect_to meetings_path
    else
      render "dreams/show"
    end
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end

  def update
    @meeting = Meeting.find(params[:id])
    if @meeting.update(meeting_params)
      redirect_to @meeting
    else
      render :edit
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
    redirect_to meetings_path
  end

  private

  def meeting_params
    params.require(:meeting).permit(:title, :start_time, :end_time)
  end
end

app/views/meetings/index.html.erb
<div class="calendar-container">
  <%= month_calendar(events: @meetings, end_attribute: :end_time) do |date, meetings| %>
    <%= date %>

<% colors = {} %>
<% meetings.each_with_index do |meeting, index| %>
  <% if index == 0 %>
    <% color = "#BAA1EB" %>
  <% elsif index == 1 %>
    <% color = "#5C2DC6" %>
  <% elsif index == 2 %>
    <% color = "#120924" %>
  <% else %>
    <% n = meetings.map { |m| m.dream.name }.uniq.size %>
    <% if colors[meeting.dream.name].nil? %>
      <% hue = index.to_f / n %>
      <% colors[meeting.dream.name] = "hsl(#{hue * 360}, 50%, 50%)" %>
    <% end %>
    <% color = colors[meeting.dream.name] %>
  <% end %>
  <%= link_to meeting_path(meeting) do %>
    <div class="meeting" style="background-color: <%= color %>;">
      <%= meeting.dream.name %>
    </div>
  <% end %>
<% end %>
<% end %>
</div>

app/views/meetings/new.html.erb
<h1>Add a new meeting</h1>
<%# <%= render "form", dream: @dream %>
<%= simple_form_for(@meetings) do |f| %>
<%= f.input :name %>
<%= f.input :start_time %>
<%= f.input :end_time %>
<% end %>