config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  get "search", to: "dreams#search"
  resources :dreams do
    resources :locations, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :meetings, only: [:new, :create]
  end
  resources :meetings, only: [:show, :index, :destroy]
  resources :chatrooms, only: [:show, :index, :new, :create] do
    resources :messages, only: [:create]
  end

  
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages

  validates :name, presence: true, uniqueness: true

  def name
    self[:name].presence || 'General'
  end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController

  def index
    @chatrooms = Chatroom.all

  end

  def show
    @chatroom = Chatroom.find(params[:id])
    puts "Chatroom: #{@chatroom.inspect}"
    @message = Message.new

    @messages = Message.where(chatroom: @chatroom)
  end

  def new
    @chatroom = Chatroom.new
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      redirect_to chatrooms_path
    else
      render :new, :unprocessable_entity
    end
  end


  private

  def chatroom_params
    params.require(:chatroom).permit(:name)
  end
end

app/views/chatrooms/_show.html.erb
<div class="cont chatroom">
  <h1><%= @chatroom.name %></h1>
    <div class="messages"
    data-chatrooms-target="messages"
    data-controller="chatrooms"
    data-chatrooms-chatroom-id-value="<%= @chatroom.id %>"
    >
      <% @chatroom.messages.each do |message| %>
        <%= render "messages/message", message: message %>
      <% end %>
    </div>

  <%= simple_form_for [@chatroom, @message], remote: true do |f| %>
    <%= f.input :content, label: false, placeholder: "Message ##{@chatroom.name}" %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %>
  <%  end %>
</div>

app/views/chatrooms/index.html.erb
<div class="two-first-div"></div>
  <%= form_with(model: Chatroom.new) do |form| %>
    <%= form.text_field :name %>
    <%= form.submit class: "btn btn-primary", data: { disable_with: "Submitting..." }, id: "submit-button" %>
  <% end %>


<div class="general-presentation-chatroom" data-controller="chatroom">
  <% @chatrooms.each do |chat|  %>
    <div class="presentation-chatroom" id="chatroom-<%= chat.id %>" data-chatroom-target="chatroom">
      <%= link_to chat.name, chatroom_path(chat.id), class: "test", data: { chatroom_id: chat.id }, data_action: "click->chatroom#show" %>
    </div>
  <% end %>
</div>


  <div>
    <%= render "chatrooms/show" %>
  </div>

app/views/chatrooms/show.html.erb
<div class="cont chatroom">
  <h1><%= @chatroom.name %></h1>
    <div class="messages"
    data-chatrooms-target="messages"
    data-controller="chatrooms"
    data-chatrooms-chatroom-id-value="<%= @chatroom.id %>"
    >
      <% @chatroom.messages.each do |message| %>
        <%= render "messages/message", message: message %>
      <% end %>
    </div>

  <%= simple_form_for [@chatroom, @message], remote: true do |f| %>
    <%= f.input :content, label: false, placeholder: "Message ##{@chatroom.name}" %>
    <%= f.submit "Send", class: "btn btn-primary mb-3" %>
  <%  end %>
</div>