config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  get "search", to: "dreams#search"
  resources :dreams do
    resources :locations, only: [:create]
    resources :likes, only: [:create, :destroy]
    resources :meetings, only: [:new, :create]
  end
  resources :meetings, only: [:show, :index, :destroy]
  resources :chatrooms, only: [:show, :index, :new, :create] do
    resources :messages, only: [:create]
  end

  
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">

</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png"%>
    <% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
            <%= link_to "Ton calendrier", meetings_path, class: "btn btn-outline-primary my-2 my-sm-0 ms-2" %>
            <%= link_to "Ajoute un rêve", new_dream_path, class: "btn btn-outline-primary my-2 my-sm-0 ms-2" %>
          <li class="nav-item">
          <%= link_to chatrooms_path, class: "nav-link" do %>
            <%= "Messages" %>
          <% end %>
          </li>

          <li class="nav-item dropdown">
              <a class="nav-link" href="#" data-bs-toggle="dropdown"><%= current_user.nickname %></a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Se déconnecter", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
            </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="all-selector">
        <%= form_with url: dreams_path, method: :get do |f| %>
          <%= f.label "rechercher votre marque" %>
          <%= f.search_field :query %>
          <%= f.submit %>
        <% end %>
    </div>
  </div>
</div>